version: '3.8'
services:
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: olive_dev
    ports:
      - "5432:5432"
    networks:
      - my_network

  app:
    build: .
    image: olive
    container_name: olive-app
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/olive_dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - my_network

networks:
    my_network:
        driver: bridge
volumes:
    postgres-db-data:
        driver: local