spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop  # Drops schema after tests
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  server:
    port: 8081
  logging:
    level:
      root: WARN
