spring:
  application:
    name: ${APPLICATION_NAME:olive}
  profiles:
    active: ${ENV:local}
  main:
    banner-mode: off
---
server:
  port: ${SERVER_PORT:8080}
---
management:
  metrics:
    system:
      enabled: false